### ISSUE TITLE
Hebrew Rendering

### ISSUE THREAD

**Issue by uriee** [AmirTugi/tea-school#12]
Helllo,

When i try to render hebrew charecters i get these kind of charecters :  `××•×¨×™ `
i had cloned the ptoject on a windows machine that has all the font installed.

is there a way to fix it?

Thanks.

**Comment by AmirTugi** [comment]
Hey!
Can you please provide me with the code you're trying to run (and maybe some environment info)?
I've had no issues with any language - it's Puppeteer which renders the HTML. So if the browser knows how to render it correctly, the lib should render it correctly as well.

**Comment by uriee** [comment]
Hello Amir,  thank you for you replay.
It is strange , when i use puppeteer nativly in my code (send it html from a browser) it works fine.
all i did was to alter some text in your invoice example and check if it renders well.
i also tried to importe an hebrew font in the invoice-pdf.scss file -

```
 @import url('https://fonts.googleapis.com/css?family=Rubik&display=swap');
 body {
   padding: 20px;
   font-family: 'Rubik' , sans-serif; ...
```
It did not fix the problem.

**Comment by oneEyedSunday** [comment]
@uriee I'm doing sth like this
```const pdfOptions = {
    format: 'A4',
    printBackground: true
  };

  const teaSchoolOptions = {
    styleOptions,
    htmlTemplatePath,
    htmlTemplateOptions: data,
    pdfOptions
  };

  // We just wait for the pdf to generate, and then the program can exit
  return TeaSchool.generatePdf(teaSchoolOptions);
```


I don't  access `page` as in your fix

**Comment by uriee** [comment]
@oneEyedSunday I did'nt fork it i just used some concepts introduced in this repo in my code.

**Comment by oneEyedSunday** [comment]
thanks. i've made necessary adjustments
