### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by oneEyedSunday** [AmirTugi/tea-school#13]
Hello @AmirTugi I'm printing something that involves emojis.
They come out mangled like this 
<img width="166" alt="Screenshot 2019-06-14 at 2 47 57 PM" src="https://user-images.githubusercontent.com/29808443/59513833-94e77e00-8eb3-11e9-9b99-91d31d6dfe13.png">

do I have to make any adjustments to the config, like encoding settings, since emojis are supposed to be unicode.

The emojis were ❎

**Comment by AmirTugi** [comment]
Hi!
That sounds weird. Like it should've indeed worked out of the box. 
Can you take a look at #12 and tell me if at helped you?

**Comment by radiumrasheed** [comment]
at what point do I call...
> `page.setContent`
instead of
`page.goto('data:text/html'...`

```javascript
module.exports = async(data, file_path) => {
  const styleOptions = {
    // Get relative path from cwd to the desired file
    file: path.resolve(__dirname, 'style.scss')
  };

  // Get relative path from cwd to the desired file
  const htmlTemplatePath = path.resolve(__dirname, file_path);

  const pdfOptions = {
    format: 'A4',
    printBackground: true
  };

  const teaSchoolOptions = {
    styleOptions,
    htmlTemplatePath,
    htmlTemplateOptions: data,
    pdfOptions
  };

  // We just wait for the pdf to generate, and then the program can exit
  return TeaSchool.generatePdf(teaSchoolOptions);
};
```

**Comment by oneEyedSunday** [comment]
#12 proved helpful thanks.
