### ISSUE TITLE
PDF Generation is cut off after # is found in the html.

### ISSUE THREAD

**Issue by ozzyonfire** [AmirTugi/tea-school#15]
Looks like it's a puppeteer issue. 

https://github.com/GoogleChrome/puppeteer/issues/3736

I fixed it by using this line before the pdf generation:
`        await page.setContent(renderedTemplate, {waitUntil: 'networkidle0'});
`

Maybe we should use setContent instead of goto? I'm not very familiar with puppeteer, so I'm not sure what the repercussions would be.

**Comment by AmirTugi** [comment]
Hey, I've updated the package to support the `setContent` of Puppeteer.
Can you tell me if the issue is now resolved?

**Comment by ozzyonfire** [comment]
Looks great! Everything is rendering properly now. Thanks, Amir.
