### ISSUE TITLE
Question: add bootstrap

### ISSUE THREAD

**Issue by Paul75** [AmirTugi/tea-school#18]
Hello,

Can I know If I can use boostrap and import it ?

I test to do in the scss file : @import 'boostrap/scss/boostrap' (I get files into directory) but not seems to works.

Thanks

**Comment by AmirTugi** [comment]
Since Tea-School uses [Node-Sass](https://github.com/sass/node-sass) directly - have you tried seeing what it generates for you?

**Comment by Paul75** [comment]
not yet ....
