### ISSUE TITLE
Using it in React

### ISSUE THREAD

**Issue by osamagoraya** [AmirTugi/tea-school#19]
Can this be used in reactjs, at frontend

**Comment by AmirTugi** [comment]
No, as Puppeteer runs only in Node.js

**Comment by osamagoraya** [comment]
Thanks. In the examples, I am not able to apply styles to table columns. I can do it in your other example of basic usage.

CONTENTS OF scss
`
$blue: #0084ff;
$blue-darker: darken($blue, 5);

body {
  padding: 20px;
  font-family: Halvetica, sans-serif;
  background: #0084ff;

  .title {
    margin-bottom: 4px;
  }

  .created-at {
    font-size: 14px;
    color: lightgray;
  }

  .comments-title {
    margin-bottom: 4px;
  }

  table {
    width: 100%;
  }

  table, tr, th, td {
    border: 1px solid black;
    background: #0084ff;
  }
  td {
    text-align: right;
    background: #0084ff;
  }
  
  

  .table-footer {
    text-align: right;
    margin: 4px 0;
    
  }
}
`
CONTENTS OF pug
`// Use !{var} to use unescaped conent
style(type="text/css") !{compiledStyle}

h1.title Invoice number ##{invoice.id}

p.created-at #{invoice.createdAt}

h3 For: #{invoice.customer.name}

table
    thead
        tr
            th #
            th Item
            th Price
    tbody
        each line in invoice.lines
            tr
                td #{line.id}
                td.blue #{line.item}
                td #{line.price}

div.table-footer Shipping: $#{invoice.shipping}
div.table-footer total: $#{invoice.total}

h3.comments-title Comments
p #{invoice.comments}
`
