### ISSUE TITLE
Protocol error (Page.printToPDF): Target closed.

### ISSUE THREAD

**Issue by opassion** [AmirTugi/tea-school#20]
It happens when I tried to generate the PDF with more than 100 images.

And here's the solution.

https://github.com/GoogleChrome/puppeteer/issues/2735#issuecomment-470309033

**Comment by AmirTugi** [comment]
Hey there @opassion!
As I'm combining packages together, I want you to have full flexibility over the configuration of each of the library being used in `Tea-School`.

Meaning - You can define `pipe: true` in the [launch options of puppeteer](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/puppeteer/index.d.ts#L2031) using the [`puppeteerOptions`](https://github.com/AmirTugi/tea-school/blob/master/src/index.ts#L13) object you may pass to `generatePdf`.

**Comment by AmirTugi** [comment]
I am closing this as I assume the problem was resolved.
Feel free to reopen in case this issue pops out again.
