### ISSUE TITLE
Convert from ts to js

### ISSUE THREAD

**Issue by osamagoraya** [AmirTugi/tea-school#21]
How can I convert it to js? I need to use it as javascript in node. Do I need to convert anything to make it work. Can you tell me what to do to change your examples to js. And can i use this package in js files?

**Comment by osamagoraya** [comment]
Please give me an example in JS. Please.

**Comment by AmirTugi** [comment]
To use it as js, you just need to remove type declarations :
```javascript
import {GeneratePdfOptions, generatePdf} from 'tea-school';
import * as path from 'path';

const options = {
    htmlTemplatePath: path.resolve(__dirname, 'pdf-template.pug'),

    // Here you put an object according to https://github.com/sass/node-sass#options 
    styleOptions: {
        file: path.resolve(__dirname, 'pdf-template.scss')
    },

    // Here you put an object according to https://pugjs.org/api/reference.html#options
    // You can add any additional key to be used as a variable in the template.
    htmlTemplateOptions: {
        name: 'Timothy'
    },

    // Here you put an object according to https://github.com/GoogleChrome/puppeteer/blob/v1.18.1/docs/api.md#pagepdfoptions
    pdfOptions: {
        // Ignore `path` to get the PDF as buffer only
        path: 'pdf-file.pdf',
        format: 'A4',
        printBackground: true
    }
}

(async () => {
    const pdfBuffer = await generatePdf(options);
})();``

**Comment by osamagoraya** [comment]
Thanks for the help. I really appreciate it. But I am not understanding it still.
I have three files .pug , .scss and .js file and an output folder. Do I need to have that file as well that is in src? and then use it like you did in examples?

**Comment by AmirTugi** [comment]
This snippet is the code you'd use to run the example.
Define the `options` wherever you want in your JS file, and then use
`const pdfBuffer = await generatePdf(options);` to create the PDF.
