### ISSUE TITLE
i couldn't run the example 

### ISSUE THREAD

**Issue by vijaybaliah** [AmirTugi/tea-school#4]
i did npm install and ran the following commands
`npm i -g typescript
  tsc examples/basic-usage/index.ts
  node examples/basic-usage/index.js`

it throwed this error

(node:46518) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'launch' of undefined
(node:46518) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

later i found that the `puppeteer_1["default"].launch()`
in (tea-school/src/index.js:59:68) is causing the issue so removed it and it started working

but no problem in the package though. It works fine

is this line important puppeteer_1["default"].launch()

**Comment by AmirTugi** [comment]
Hey, thanks for posting this issue.
I have indeed reproduced this.
I've patched this in this [commit](https://github.com/AmirTugi/tea-school/commit/cd36caecb650bcd32674bd082019e824ccedebf0)

I added a `tsconfig.json` for easier transpilation and updated the doc.
Thanks! :)
